apiVersion: v1
kind: Namespace
metadata:
  name: lab
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  namespace: lab
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend: 
    serviceName: dev-example-svc
    servicePort: 80
  rules:
  - host: test.devsecol.site
    http:
      paths:
      - path: /test/*
        backend:
          serviceName: test-example-svc
          servicePort: 80
  - http:
      paths:
      - path: /dev/*
        backend:
          serviceName: dev-example-svc
          servicePort: 80

# Changes for Kubernetes 1.18
# apiVersion: networking.k8s.io/v1
# spec:
#  defaultBackend: 
#    service:
#      name: dev-example-svc
#      port: 80
#  rules:
#  - http:
#      paths:
#      - path: /dev
#        pathType: Prefix
#        backend:
#          service:
#            name: dev-example-svc
#            port:
#              number: 80